### GET ALL
GET http://localhost:3001/api/persons/

### GET ONE
GET http://localhost:3001/api/persons/66ad11976ae693c9c1a02138

### CREATE ONE
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Mauri3",
    "number": 123456
}

### DELETE ONE
DELETE http://localhost:3001/api/persons/66ad11976ae693c9c1a02138

### MODIFY ONE
PUT http://localhost:3001/api/persons/66ad11976ae693c9c1a02138
Content-Type: application/json

{
    "name": "Mauri3",
    "number": 654321
}